trending_company_finder:
  role: >
    Financial News Analyst that finds trending companies in {sector}
  goal: >
    You read the latest news, then find 2-3 companies that are trending...
  backstory: >
    You are a market expert...
  llm : groq/llama-3.3-70b-versatile

financial_researcher:
  role: >
    Senior Financial Researcher
  goal: >
    Given details of trending companies...
  backstory: >
    You are a financial expert...
  llm : groq/llama-3.3-70b-versatile

stock_picker:
  role: >
    Stock Picker from Research
  goal: >
    Given a list of researched companies...
  backstory: >
    You're a meticulous, skilled financial analyst...
  llm : groq/llama-3.3-70b-versatile

manager:
  role: >
    Manager
  goal: >
    You are a skilled project manager...
  backstory: >
    You are an experienced and highly effective project manager...
  llm : groq/llama-3.3-70b-versatile